https://github.com/rougier/numpy-100/blob/master/100%20Numpy%20exercises%20with%20hint.ipynb

1: Import the numpy package under the name np (★☆☆)

In [1]:
import numpy as np

2: Print the numpy version and the configuration (★☆☆)

In [2]:
np.__version__

'1.13.3'

In [3]:
np.show_config

<function numpy.__config__.show>

3: Create a null vector of size 10 (★☆☆)

In [4]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

4: How to find the memory size of any array (★☆☆)

In [13]:
a = np.ones(20)
# In general, you can simply query the nbytes attribute for the total memory requirement of an array, 
# and itemsize for the size of a single element in bytes.

In [12]:
print(a.nbytes)
print(a.itemsize)

160
8


5: How to get the documentation of the numpy add function from the command line? (★☆☆)

In [14]:
?np.add

In [15]:
help(np.add)

Help on ufunc object:

add = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  Calling ufuncs:
 |  ===============
 |  
 |  op(*x[, out], where=True, **kwargs)
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array o

python -c "import numpy; numpy.info(numpy.add)"

6: Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [16]:
a = np.zeros(10)
a[4] = 1
print(a)

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


7: Create a vector with values ranging from 10 to 49 (★☆☆)

In [25]:
a = np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


8: Reverse a vector (first element becomes last)

In [48]:
a = np.arange(10)
print(a)
print(a[::-1])
print(-np.sort(-a))

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]
[9 8 7 6 5 4 3 2 1 0]


9: Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [49]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

10: Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [52]:
a = np.array([1,2,0,0,4,0])
np.where(a != 0)

(array([0, 1, 4]),)

11: Create a 3x3 identity matrix (★☆☆)

In [54]:
np.eye(3,3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

12: Create a 3x3x3 array with random values (★☆☆)

In [60]:
np.random.rand(3,3,3)

array([[[ 0.88289532,  0.26672535,  0.62629227],
        [ 0.16373246,  0.93227222,  0.04143009],
        [ 0.76501706,  0.88508637,  0.86347791]],

       [[ 0.28185427,  0.60490915,  0.44909189],
        [ 0.6106241 ,  0.60551101,  0.31156408],
        [ 0.14501   ,  0.00946461,  0.68668713]],

       [[ 0.17638627,  0.77659589,  0.87420843],
        [ 0.17975411,  0.45117523,  0.13834321],
        [ 0.56202054,  0.62984985,  0.31434349]]])

13: Create a 10x10 array with random values and find the minimum and maximum values 

In [61]:
a = np.random.rand(10,10)
print(a)

[[ 0.37277922  0.95449249  0.31892355  0.30601662  0.58774872  0.36784665
   0.48176316  0.7956405   0.26778359  0.77412925]
 [ 0.39326234  0.53162059  0.25934957  0.22401872  0.52177845  0.51721934
   0.75865068  0.61990487  0.70969346  0.53025254]
 [ 0.96817462  0.84231082  0.20218573  0.72107307  0.59500146  0.86794384
   0.55403149  0.70972742  0.47467546  0.41931439]
 [ 0.54001581  0.09516722  0.84315164  0.86106433  0.38398273  0.37868226
   0.88430338  0.75621297  0.35580501  0.71265709]
 [ 0.3581538   0.19362668  0.69331037  0.17225775  0.44262759  0.3009325
   0.17627964  0.43188926  0.92599636  0.67831024]
 [ 0.84848433  0.22642921  0.94834275  0.54225459  0.32710236  0.7839315
   0.39251499  0.02173133  0.58179748  0.96670486]
 [ 0.39105169  0.77149939  0.14031351  0.76604418  0.82530482  0.69997354
   0.94545008  0.5886398   0.62120441  0.48545185]
 [ 0.1131361   0.82100436  0.67761462  0.30853816  0.882681    0.25563409
   0.17300854  0.06650469  0.0481129   0.61493161]
 [

In [64]:
print(np.max(a))
print(np.min(a))

0.999582108491
0.0217313278383


14: Create a random vector of size 30 and find the mean value (★☆☆)

In [66]:
a = np.random.rand(30)
print(a)

[ 0.24608234  0.67601334  0.58776452  0.64736903  0.99743521  0.26662458
  0.80751865  0.06409383  0.10201248  0.24118058  0.10068455  0.18853728
  0.5954567   0.32715225  0.43083219  0.33342086  0.91437093  0.74551157
  0.51158335  0.38147625  0.56432204  0.10120451  0.90291805  0.40648926
  0.63840345  0.46168951  0.71505566  0.16298896  0.83301218  0.58544857]


In [67]:
np.mean(a)

0.48455508854990853

15: Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [72]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


16: How to add a border (filled with 0's) around an existing array? (★☆☆)

In [84]:
a = np.random.rand(5,5)
print(a)

[[ 0.31720915  0.21175011  0.97201054  0.57759979  0.63660228]
 [ 0.94647036  0.67168328  0.58044491  0.77453892  0.0541145 ]
 [ 0.01008054  0.05043569  0.70273233  0.39719309  0.31977869]
 [ 0.48948915  0.52470349  0.66650705  0.09795385  0.5943684 ]
 [ 0.11965539  0.41185216  0.15179955  0.51653782  0.95482986]]


In [82]:
a[:,0] = 0
a[:,-1] = 0
a[0,:] = 0
a[-1,:] = 0
print(a)

[[ 0.          0.          0.          0.          0.        ]
 [ 0.          0.31861045  0.28042474  0.45147692  0.        ]
 [ 0.          0.51371793  0.92152854  0.63622874  0.        ]
 [ 0.          0.00640616  0.32644275  0.25168731  0.        ]
 [ 0.          0.          0.          0.          0.        ]]


17: What is the result of the following expression? (★☆☆)

0 * np.nan

np.nan == np.nan

np.inf > np.nan

np.nan - np.nan

0.3 == 3 * 0.1

In [92]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


18: Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [111]:
np.diag([1,2,3,4],k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

19: Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [136]:
a = np.zeros((8,8))
print(a)

[[ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]]


In [141]:
a[::2,::2] = 1
a[1::2,1::2] = 1
print(a)

[[ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]]


20: Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [144]:
x = np.arange(6*7*8).reshape(6,7,8)
print(x)

[[[  0   1   2   3   4   5   6   7]
  [  8   9  10  11  12  13  14  15]
  [ 16  17  18  19  20  21  22  23]
  [ 24  25  26  27  28  29  30  31]
  [ 32  33  34  35  36  37  38  39]
  [ 40  41  42  43  44  45  46  47]
  [ 48  49  50  51  52  53  54  55]]

 [[ 56  57  58  59  60  61  62  63]
  [ 64  65  66  67  68  69  70  71]
  [ 72  73  74  75  76  77  78  79]
  [ 80  81  82  83  84  85  86  87]
  [ 88  89  90  91  92  93  94  95]
  [ 96  97  98  99 100 101 102 103]
  [104 105 106 107 108 109 110 111]]

 [[112 113 114 115 116 117 118 119]
  [120 121 122 123 124 125 126 127]
  [128 129 130 131 132 133 134 135]
  [136 137 138 139 140 141 142 143]
  [144 145 146 147 148 149 150 151]
  [152 153 154 155 156 157 158 159]
  [160 161 162 163 164 165 166 167]]

 [[168 169 170 171 172 173 174 175]
  [176 177 178 179 180 181 182 183]
  [184 185 186 187 188 189 190 191]
  [192 193 194 195 196 197 198 199]
  [200 201 202 203 204 205 206 207]
  [208 209 210 211 212 213 214 215]
  [216 217 218 219 220

In [145]:
np.where(x == 100)

(array([1]), array([5]), array([4]))

21: Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [147]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [149]:
a = np.ones((8,8))
print(a)
a[::2,::2] = 0
a[1::2,1::2] = 0
print(a)

[[ 1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.]]
[[ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]]


22: Normalize a 5x5 random matrix (★☆☆)

In [157]:
x = np.random.rand(5,5)
print(x)
xmax = np.max(x)
xmin = np.min(x)
print(xmax, xmin) 
print((x - xmin)/(np.max(x) - np.min(x)))

[[ 0.90470616  0.26134743  0.75456026  0.86399557  0.4516576 ]
 [ 0.76599413  0.54719516  0.13400338  0.8137656   0.47276638]
 [ 0.91192754  0.34212142  0.05680572  0.5986608   0.36140508]
 [ 0.92768314  0.49115971  0.6961454   0.60079359  0.81017618]
 [ 0.16880753  0.05918136  0.43075858  0.54969306  0.13115648]]
0.927683135781 0.0568057200881
[[ 0.97361629  0.23486854  0.80120868  0.92686966  0.45339548]
 [ 0.81433781  0.56309812  0.08864354  0.86919222  0.477634  ]
 [ 0.98190837  0.32761867  0.          0.62219443  0.34976147]
 [ 1.          0.49875446  0.73413281  0.62464344  0.86507061]
 [ 0.12860801  0.00272787  0.42939782  0.56596638  0.08537455]]


23: Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [159]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

24: Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [161]:
x = np.random.rand(5,3); y = np.random.rand(3,2)
print(x.shape, y.shape)

(5, 3) (3, 2)


In [162]:
np.dot(x,y)

array([[ 0.73458589,  1.03922352],
       [ 0.14679837,  0.25517584],
       [ 0.62854631,  1.04654438],
       [ 0.25512589,  0.38500708],
       [ 0.17135352,  0.33909721]])

25: Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [199]:
a = np.arange(20)
print(a)
a[(a >= 3) & (a <= 8)] = -1
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10 11 12 13 14 15 16 17 18 19]


26: What is the output of the following script? (★☆☆)

print(sum(range(5),-1))

from numpy import *

print(sum(range(5),-1))

27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

Z**Z

2 << Z >> 2

Z <- Z

1j*Z

Z/1/1

Z<Z>Z

29: How to round away from zero a float array ? (★☆☆)

In [221]:
Z = np.random.uniform(-10,+10,10)
print(np.round(Z))

[ 1. -5.  9. -1. -2.  5. -1. -2. -8.  4.]


30: How to find common values between two arrays? (★☆☆)

In [223]:
a = np.arange(20)
b = np.arange(15,26)
print(a,b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] [15 16 17 18 19 20 21 22 23 24 25]


In [226]:
np.intersect1d(a,b)

array([15, 16, 17, 18, 19])

31: How to ignore all numpy warnings (not recommended)? (★☆☆)

In [229]:
np.seterr(all='ignore')

{'divide': 'warn', 'invalid': 'warn', 'over': 'warn', 'under': 'ignore'}

In [231]:
np.seterr()

{'divide': 'ignore', 'invalid': 'ignore', 'over': 'ignore', 'under': 'ignore'}

32: Is the following expressions true? (★☆☆)

np.sqrt(-1) == np.emath.sqrt(-1)

33: How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [237]:
a = np.datetime64
a.today()

AttributeError: type object 'numpy.datetime64' has no attribute 'today'

In [238]:
import tensorflow

ModuleNotFoundError: No module named 'tensorflow'

In [239]:
2 + 2

4